#.travis.yml

language: node_js
node_js:
  - "7.1.0"

branches:
  only:
    - master

before_install:
  - cd ./ng-app

before_script:
  - npm install

script:
  - ng lint
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
