#.travis.yml
sudo: required
dist: trusty
language: node_js
node_js:
  - "8.2.1"

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd ./ng-app

before_script:
  - npm install

script:
  - ng test --single-run
  - ng lint --type-check
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
